spring.application.name=EMT_Lab_Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/emt_lab
spring.datasource.username=postgres
spring.datasource.password=postgre

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

