spring.application.name=EMT_Lab_Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/emt_lab
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.materialized-view.refresh-rate=60000
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

